CREATE TABLE bookmark(
`token` varchar(255)  NOT NULL DEFAULT '' COMMENT '用户身份标识',
`bookmark` text NOT NULL DEFAULT '' COMMENT '内容类型' ,
`ctime`  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '创建时间',
`mtime`  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据修改时间',
 PRIMARY KEY (`token`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='书签内容表';

root
Df2u)iu/Evdi

GRANT USAGE ON *.* TO 'user01'@'localhost' IDENTIFIED BY 'a9f5b812b65fc40c94625DW)`/sfE' WITH GRANT OPTION
