CREATE TABLE user_geo (
  uid SERIAL NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  user_name VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户名称',
  geom GEOMETRY(Point, 4326),
  insert_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '写入时间',
  update_time timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (uid)
);